site_name: WEB-programming
nav:
    - Home: index.md
    - 1 lab:
      - Task 1: docs/LR1/task1.md
      - Task 2: docs/LR1/task2.md
      - Task 3: docs/LR1/task3.md
      - Task 4: docs/LR1/task4.md
      - Task 5: docs/LR1/task5.md
theme:
    name: readthedocs